<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ledger\Ledgance.Accounting.Ledger.Application\Ledgance.Accounting.Ledger.Application.csproj" />
    <ProjectReference Include="..\Ledgance.Accounting.AI.Domain\Ledgance.Accounting.AI.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Ledgance.Shared.Application\Ledgance.Shared.Application.csproj" />
  </ItemGroup>

</Project>
