<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledgance.Accounting.AI.Application\Ledgance.Accounting.AI.Application.csproj" />
    <ProjectReference Include="..\..\..\..\Shared\Ledgance.Shared.Infrastructure\Ledgance.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
