import type {
  ActivityItem,
  Client,
  Document,
  Engagement,
  Organization,
  TrialBalanceEntry,
  User,
  WorkingPaper,
} from "./types";

export const currentUser: User = {
  id: "u1",
  name: "Jordan Avery",
  email: "jordan.avery@ledgance.io",
  role: "manager",
  initials: "JA",
};

export const organizations: Organization[] = [
  {
    id: "org1",
    name: "Northgate Advisory",
    logoColor: "#0ea5e9",
    plan: "professional",
  },
  {
    id: "org2",
    name: "Meridian Audit Partners",
    logoColor: "#10b981",
    plan: "enterprise",
  },
];

export const clients: Client[] = [
  {
    id: "c1",
    name: "Halcyon Manufacturing Co.",
    industry: "Industrial Manufacturing",
    contactName: "Priya Nair",
    contactEmail: "priya.nair@halcyon.co",
    contactPhone: "+1 (415) 555-0142",
    website: "halcyon.co",
    address: "1800 Foundry Blvd, Pittsburgh, PA",
    createdAt: "2024-02-11",
    logoColor: "#0ea5e9",
  },
  {
    id: "c2",
    name: "Brightwave Logistics",
    industry: "Transportation & Logistics",
    contactName: "Marcus Lee",
    contactEmail: "marcus.lee@brightwave.io",
    contactPhone: "+1 (312) 555-0199",
    website: "brightwave.io",
    address: "920 Harbor Pkwy, Long Beach, CA",
    createdAt: "2024-05-03",
    logoColor: "#10b981",
  },
  {
    id: "c3",
    name: "Solstice Health Group",
    industry: "Healthcare",
    contactName: "Dr. Elena Cruz",
    contactEmail: "e.cruz@solsticehealth.com",
    contactPhone: "+1 (617) 555-0110",
    website: "solsticehealth.com",
    address: "55 Wellness Way, Boston, MA",
    createdAt: "2024-08-19",
    logoColor: "#f59e0b",
  },
  {
    id: "c4",
    name: "Cedar & Ash Retail",
    industry: "Retail & E-commerce",
    contactName: "Tomás Rivera",
    contactEmail: "tomas@cedarash.com",
    contactPhone: "+1 (206) 555-0177",
    website: "cedarash.com",
    address: "12 Market St, Portland, OR",
    createdAt: "2025-01-22",
    logoColor: "#8b5cf6",
  },
];

export const engagements: Engagement[] = [
  {
    id: "e1",
    clientId: "c1",
    name: "FY2025 Statutory Audit",
    type: "financial-statement",
    status: "fieldwork",
    partner: "Sarah Whitman",
    manager: "Jordan Avery",
    fiscalYearEnd: "2025-03-31",
    budgetHours: 640,
    actualHours: 412,
    progress: 62,
    startDate: "2025-04-01",
    endDate: "2025-06-30",
    team: ["Sarah Whitman", "Jordan Avery", "Kai Patel", "Lina Ortiz"],
  },
  {
    id: "e2",
    clientId: "c1",
    name: "Q4 Internal Controls Review",
    type: "internal",
    status: "review",
    partner: "Sarah Whitman",
    manager: "Jordan Avery",
    fiscalYearEnd: "2024-12-31",
    budgetHours: 220,
    actualHours: 198,
    progress: 88,
    startDate: "2025-01-15",
    endDate: "2025-03-15",
    team: ["Jordan Avery", "Kai Patel"],
  },
  {
    id: "e3",
    clientId: "c2",
    name: "FY2024 Financial Statement Audit",
    type: "financial-statement",
    status: "sign-off",
    partner: "David Cho",
    manager: "Jordan Avery",
    fiscalYearEnd: "2024-12-31",
    budgetHours: 580,
    actualHours: 541,
    progress: 95,
    startDate: "2025-01-10",
    endDate: "2025-03-28",
    team: ["David Cho", "Jordan Avery", "Maya Singh", "Ben Foster"],
  },
  {
    id: "e4",
    clientId: "c2",
    name: "SOC 1 Compliance Audit",
    type: "compliance",
    status: "planning",
    partner: "David Cho",
    manager: "Jordan Avery",
    fiscalYearEnd: "2025-06-30",
    budgetHours: 320,
    actualHours: 24,
    progress: 8,
    startDate: "2025-07-01",
    endDate: "2025-09-30",
    team: ["David Cho", "Maya Singh"],
  },
  {
    id: "e5",
    clientId: "c3",
    name: "FY2025 Audit — Initial Year",
    type: "financial-statement",
    status: "planning",
    partner: "Sarah Whitman",
    manager: "Jordan Avery",
    fiscalYearEnd: "2025-12-31",
    budgetHours: 780,
    actualHours: 86,
    progress: 14,
    startDate: "2025-06-01",
    endDate: "2026-02-28",
    team: ["Sarah Whitman", "Jordan Avery", "Lina Ortiz", "Ben Foster"],
  },
  {
    id: "e6",
    clientId: "c4",
    name: "FY2024 Review Engagement",
    type: "review",
    status: "completed",
    partner: "David Cho",
    manager: "Jordan Avery",
    fiscalYearEnd: "2024-12-31",
    budgetHours: 160,
    actualHours: 152,
    progress: 100,
    startDate: "2025-02-01",
    endDate: "2025-03-20",
    team: ["David Cho", "Maya Singh"],
  },
];

export const documents: Document[] = [
  {
    id: "d1",
    engagementId: "e1",
    name: "Bank Confirmations — First National",
    category: "evidence",
    type: "PDF",
    status: "current",
    uploadedBy: "Kai Patel",
    uploadedAt: "2025-05-12",
    size: "1.2 MB",
    tags: ["cash", "confirmation", "bank"],
    versions: [
      {
        version: 3,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-05-12",
        size: "1.2 MB",
        note: "Updated with bank-confirmed balances",
      },
      {
        version: 2,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-05-04",
        size: "1.1 MB",
        note: "Corrected account number formatting",
      },
      {
        version: 1,
        uploadedBy: "Lina Ortiz",
        uploadedAt: "2025-04-28",
        size: "1.0 MB",
        note: "Initial confirmation request",
      },
    ],
  },
  {
    id: "d2",
    engagementId: "e1",
    name: "Trial Balance — FY2025 Unadjusted",
    category: "financial",
    type: "XLSX",
    status: "current",
    uploadedBy: "Jordan Avery",
    uploadedAt: "2025-04-15",
    size: "842 KB",
    tags: ["trial-balance", "gl", "unadjusted"],
    versions: [
      {
        version: 2,
        uploadedBy: "Jordan Avery",
        uploadedAt: "2025-04-15",
        size: "842 KB",
        note: "Re-exported after GL reclass",
      },
      {
        version: 1,
        uploadedBy: "Jordan Avery",
        uploadedAt: "2025-04-02",
        size: "798 KB",
        note: "Initial TB export",
      },
    ],
  },
  {
    id: "d3",
    engagementId: "e1",
    name: "AR Aged Trial Balance",
    category: "evidence",
    type: "XLSX",
    status: "current",
    uploadedBy: "Lina Ortiz",
    uploadedAt: "2025-05-08",
    size: "640 KB",
    tags: ["ar", "aging", "receivables"],
    versions: [
      {
        version: 1,
        uploadedBy: "Lina Ortiz",
        uploadedAt: "2025-05-08",
        size: "640 KB",
        note: "Aged AR as of 4/30",
      },
    ],
  },
  {
    id: "d4",
    engagementId: "e1",
    name: "Engagement Letter — Signed",
    category: "correspondence",
    type: "PDF",
    status: "current",
    uploadedBy: "Jordan Avery",
    uploadedAt: "2025-04-01",
    size: "320 KB",
    tags: ["legal", "engagement-letter"],
    versions: [
      {
        version: 1,
        uploadedBy: "Jordan Avery",
        uploadedAt: "2025-04-01",
        size: "320 KB",
        note: "Countersigned engagement letter",
      },
    ],
  },
  {
    id: "d5",
    engagementId: "e1",
    name: "Inventory Count Observation Notes",
    category: "supporting",
    type: "DOCX",
    status: "current",
    uploadedBy: "Kai Patel",
    uploadedAt: "2025-05-20",
    size: "210 KB",
    tags: ["inventory", "observation", "fieldwork"],
    versions: [
      {
        version: 2,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-05-20",
        size: "210 KB",
        note: "Added second site observations",
      },
      {
        version: 1,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-05-15",
        size: "180 KB",
        note: "Initial count notes",
      },
    ],
  },
  {
    id: "d6",
    engagementId: "e3",
    name: "Management Representation Letter",
    category: "correspondence",
    type: "PDF",
    status: "current",
    uploadedBy: "Maya Singh",
    uploadedAt: "2025-03-10",
    size: "280 KB",
    tags: ["representation", "management"],
    versions: [
      {
        version: 1,
        uploadedBy: "Maya Singh",
        uploadedAt: "2025-03-10",
        size: "280 KB",
        note: "Signed rep letter",
      },
    ],
  },
  {
    id: "d7",
    engagementId: "e3",
    name: "Fixed Asset Roll-Forward",
    category: "financial",
    type: "XLSX",
    status: "current",
    uploadedBy: "Ben Foster",
    uploadedAt: "2025-02-22",
    size: "1.4 MB",
    tags: ["ppe", "fixed-assets", "rollforward"],
    versions: [
      {
        version: 2,
        uploadedBy: "Ben Foster",
        uploadedAt: "2025-02-22",
        size: "1.4 MB",
        note: "Added disposals schedule",
      },
      {
        version: 1,
        uploadedBy: "Ben Foster",
        uploadedAt: "2025-02-10",
        size: "1.1 MB",
        note: "Initial roll-forward",
      },
    ],
  },
  {
    id: "d8",
    engagementId: "e2",
    name: "Controls Testing Matrix",
    category: "supporting",
    type: "XLSX",
    status: "current",
    uploadedBy: "Kai Patel",
    uploadedAt: "2025-02-15",
    size: "920 KB",
    tags: ["controls", "testing", "icfr"],
    versions: [
      {
        version: 3,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-02-15",
        size: "920 KB",
        note: "Added population completeness test",
      },
      {
        version: 2,
        uploadedBy: "Kai Patel",
        uploadedAt: "2025-02-01",
        size: "780 KB",
        note: "Revised sample sizes",
      },
      {
        version: 1,
        uploadedBy: "Jordan Avery",
        uploadedAt: "2025-01-20",
        size: "650 KB",
        note: "Initial matrix",
      },
    ],
  },
];

export const workingPapers: WorkingPaper[] = [
  {
    id: "wp1",
    engagementId: "e1",
    reference: "A-1",
    title: "Cash & Cash Equivalents",
    area: "Cash",
    description:
      "Confirmation of bank balances, reconciliation of GL to bank statements, and testing of cash transfers at year-end.",
    preparedBy: "Kai Patel",
    reviewedBy: "Jordan Avery",
    approvedBy: null,
    signOffStatus: "reviewed",
    preparedAt: "2025-05-14",
    reviewedAt: "2025-05-18",
    approvedAt: null,
    conclusion:
      "Cash balances are fairly stated. No material exceptions noted on bank confirmations. Two reconciling items cleared within 30 days of year-end.",
    riskLevel: "low",
    reviewNotes: [
      {
        id: "rn1",
        author: "Jordan Avery",
        authorInitials: "JA",
        createdAt: "2025-05-16",
        body: "Please add the cutoff bank statement for the First National account and tie to the confirmation.",
        status: "resolved",
        reply:
          "Added as version 3 of Bank Confirmations document. Ties to confirmed balance.",
        replyAuthor: "Kai Patel",
        replyAt: "2025-05-19",
      },
      {
        id: "rn2",
        author: "Jordan Avery",
        authorInitials: "JA",
        createdAt: "2025-05-17",
        body: "The wire transfer on 3/28 needs a trace to the subsequent deposit — please document.",
        status: "open",
      },
    ],
    crossReferences: [
      {
        id: "xr1",
        fromPaper: "A-1",
        toPaper: "A-2",
        label: "Bank Confirmation — First National",
        type: "supports",
      },
      {
        id: "xr2",
        fromPaper: "A-1",
        toPaper: "B-3",
        label: "Cash in Transit reconciliation",
        type: "reconciles",
      },
    ],
  },
  {
    id: "wp2",
    engagementId: "e1",
    reference: "A-2",
    title: "Bank Confirmations Summary",
    area: "Cash",
    description:
      "Summary of all bank confirmation responses and matching to general ledger balances.",
    preparedBy: "Kai Patel",
    reviewedBy: null,
    approvedBy: null,
    signOffStatus: "prepared",
    preparedAt: "2025-05-13",
    reviewedAt: null,
    approvedAt: null,
    conclusion:
      "All six bank accounts confirmed. One minor timing difference on the operating account resolved.",
    riskLevel: "low",
    reviewNotes: [],
    crossReferences: [
      {
        id: "xr3",
        fromPaper: "A-2",
        toPaper: "A-1",
        label: "Cash lead sheet",
        type: "references",
      },
    ],
  },
  {
    id: "wp3",
    engagementId: "e1",
    reference: "B-1",
    title: "Accounts Receivable — Aging",
    area: "Receivables",
    description:
      "Testing of AR aging, evaluation of allowance for doubtful accounts, and subsequent cash receipts testing.",
    preparedBy: "Lina Ortiz",
    reviewedBy: "Jordan Avery",
    approvedBy: null,
    signOffStatus: "reviewed",
    preparedAt: "2025-05-10",
    reviewedAt: "2025-05-15",
    approvedAt: null,
    conclusion:
      "AR is fairly stated. Allowance methodology consistent with prior year. Subsequent cash receipts confirm collectibility of 92% of year-end balance.",
    riskLevel: "medium",
    reviewNotes: [
      {
        id: "rn3",
        author: "Jordan Avery",
        authorInitials: "JA",
        createdAt: "2025-05-14",
        body: "The top 5 customer balances need individual confirmations sent. Please log confirmation dates.",
        status: "cleared",
        reply:
          "Confirmations sent 5/15. Responses logged in the AR confirmation tracker.",
        replyAuthor: "Lina Ortiz",
        replyAt: "2025-05-16",
      },
    ],
    crossReferences: [
      {
        id: "xr4",
        fromPaper: "B-1",
        toPaper: "B-2",
        label: "AR Confirmation Tracker",
        type: "supports",
      },
      {
        id: "xr5",
        fromPaper: "B-1",
        toPaper: "A-1",
        label: "Subsequent cash receipts",
        type: "reconciles",
      },
    ],
  },
  {
    id: "wp4",
    engagementId: "e1",
    reference: "C-1",
    title: "Inventory — Existence & Valuation",
    area: "Inventory",
    description:
      "Observation of physical inventory count, testing of standard cost variances, and lower-of-cost-or-market testing.",
    preparedBy: "Kai Patel",
    reviewedBy: null,
    approvedBy: null,
    signOffStatus: "pending",
    preparedAt: null,
    reviewedAt: null,
    approvedAt: null,
    conclusion: "",
    riskLevel: "high",
    reviewNotes: [],
    crossReferences: [],
  },
  {
    id: "wp5",
    engagementId: "e1",
    reference: "D-1",
    title: "Revenue Recognition Testing",
    area: "Revenue",
    description:
      "Walkthrough of revenue process, testing of revenue cutoff, and evaluation of performance obligations.",
    preparedBy: "Lina Ortiz",
    reviewedBy: null,
    approvedBy: null,
    signOffStatus: "pending",
    preparedAt: null,
    reviewedAt: null,
    approvedAt: null,
    conclusion: "",
    riskLevel: "high",
    reviewNotes: [],
    crossReferences: [],
  },
  {
    id: "wp6",
    engagementId: "e3",
    reference: "F-1",
    title: "Fixed Assets Roll-Forward",
    area: "Property, Plant & Equipment",
    description:
      "Roll-forward of PPE balances, testing of additions and disposals, and depreciation recalculation.",
    preparedBy: "Ben Foster",
    reviewedBy: "Jordan Avery",
    approvedBy: "David Cho",
    signOffStatus: "approved",
    preparedAt: "2025-02-12",
    reviewedAt: "2025-02-25",
    approvedAt: "2025-03-05",
    conclusion:
      "PPE is fairly stated. No material exceptions. Depreciation recalculated with no differences exceeding performance materiality.",
    riskLevel: "low",
    reviewNotes: [
      {
        id: "rn4",
        author: "Jordan Avery",
        authorInitials: "JA",
        createdAt: "2025-02-20",
        body: "Please tie the disposal proceeds to the bank deposit for the two retired forklifts.",
        status: "resolved",
        reply:
          "Traced to bank deposit on 11/14. Supporting doc added to evidence folder.",
        replyAuthor: "Ben Foster",
        replyAt: "2025-02-23",
      },
    ],
    crossReferences: [
      {
        id: "xr6",
        fromPaper: "F-1",
        toPaper: "F-2",
        label: "Depreciation schedule",
        type: "supports",
      },
    ],
  },
];

export const trialBalance: TrialBalanceEntry[] = [
  {
    id: "tb1",
    accountNumber: "1000",
    accountName: "Cash — Operating Account",
    debit: 1245800,
    credit: 0,
    mapping: "Cash and cash equivalents",
    mappingStatus: "mapped",
    assertion: "Existence; Completeness",
    risk: "low",
  },
  {
    id: "tb2",
    accountNumber: "1010",
    accountName: "Cash — Payroll Account",
    debit: 184200,
    credit: 0,
    mapping: "Cash and cash equivalents",
    mappingStatus: "mapped",
    assertion: "Existence; Completeness",
    risk: "low",
  },
  {
    id: "tb3",
    accountNumber: "1020",
    accountName: "Petty Cash",
    debit: 2500,
    credit: 0,
    mapping: "Cash and cash equivalents",
    mappingStatus: "mapped",
    assertion: "Existence",
    risk: "low",
  },
  {
    id: "tb4",
    accountNumber: "1100",
    accountName: "Accounts Receivable — Trade",
    debit: 3845600,
    credit: 0,
    mapping: "Accounts receivable, net",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation; Completeness",
    risk: "high",
  },
  {
    id: "tb5",
    accountNumber: "1110",
    accountName: "Allowance for Doubtful Accounts",
    debit: 0,
    credit: 192000,
    mapping: "Accounts receivable, net",
    mappingStatus: "mapped",
    assertion: "Valuation",
    risk: "medium",
  },
  {
    id: "tb6",
    accountNumber: "1200",
    accountName: "Inventory — Raw Materials",
    debit: 980400,
    credit: 0,
    mapping: "Inventory",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "high",
  },
  {
    id: "tb7",
    accountNumber: "1210",
    accountName: "Inventory — Work in Process",
    debit: 1450200,
    credit: 0,
    mapping: "Inventory",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "high",
  },
  {
    id: "tb8",
    accountNumber: "1220",
    accountName: "Inventory — Finished Goods",
    debit: 2110800,
    credit: 0,
    mapping: "Inventory",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "high",
  },
  {
    id: "tb9",
    accountNumber: "1300",
    accountName: "Prepaid Insurance",
    debit: 86400,
    credit: 0,
    mapping: "Prepaid expenses",
    mappingStatus: "mapped",
    assertion: "Existence; Accuracy",
    risk: "low",
  },
  {
    id: "tb10",
    accountNumber: "1310",
    accountName: "Prepaid Rent",
    debit: 48000,
    credit: 0,
    mapping: "Prepaid expenses",
    mappingStatus: "mapped",
    assertion: "Existence; Accuracy",
    risk: "low",
  },
  {
    id: "tb11",
    accountNumber: "1400",
    accountName: "Land",
    debit: 850000,
    credit: 0,
    mapping: "Property, plant and equipment",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "low",
  },
  {
    id: "tb12",
    accountNumber: "1410",
    accountName: "Buildings",
    debit: 4200000,
    credit: 0,
    mapping: "Property, plant and equipment",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "low",
  },
  {
    id: "tb13",
    accountNumber: "1420",
    accountName: "Machinery & Equipment",
    debit: 6850000,
    credit: 0,
    mapping: "Property, plant and equipment",
    mappingStatus: "mapped",
    assertion: "Existence; Valuation",
    risk: "medium",
  },
  {
    id: "tb14",
    accountNumber: "1430",
    accountName: "Accumulated Depreciation",
    debit: 0,
    credit: 3210400,
    mapping: "Property, plant and equipment",
    mappingStatus: "mapped",
    assertion: "Valuation",
    risk: "low",
  },
  {
    id: "tb15",
    accountNumber: "1500",
    accountName: "Intangible Assets — Software",
    debit: 320000,
    credit: 0,
    mapping: null,
    mappingStatus: "unmapped",
    assertion: null,
    risk: "medium",
  },
  {
    id: "tb16",
    accountNumber: "2000",
    accountName: "Accounts Payable — Trade",
    debit: 0,
    credit: 1920400,
    mapping: "Accounts payable",
    mappingStatus: "mapped",
    assertion: "Completeness; Existence",
    risk: "medium",
  },
  {
    id: "tb17",
    accountNumber: "2010",
    accountName: "Accrued Liabilities",
    debit: 0,
    credit: 384200,
    mapping: "Accrued liabilities",
    mappingStatus: "mapped",
    assertion: "Completeness; Existence",
    risk: "medium",
  },
  {
    id: "tb18",
    accountNumber: "2020",
    accountName: "Accrued Payroll",
    debit: 0,
    credit: 412800,
    mapping: "Accrued liabilities",
    mappingStatus: "mapped",
    assertion: "Completeness; Existence",
    risk: "medium",
  },
  {
    id: "tb19",
    accountNumber: "2100",
    accountName: "Short-Term Debt",
    debit: 0,
    credit: 1200000,
    mapping: "Short-term debt",
    mappingStatus: "mapped",
    assertion: "Completeness; Classification",
    risk: "high",
  },
  {
    id: "tb20",
    accountNumber: "2500",
    accountName: "Deferred Revenue",
    debit: 0,
    credit: 580000,
    mapping: "Deferred revenue",
    mappingStatus: "mapped",
    assertion: "Completeness; Valuation",
    risk: "medium",
  },
  {
    id: "tb21",
    accountNumber: "3000",
    accountName: "Common Stock",
    debit: 0,
    credit: 1000000,
    mapping: "Common stock",
    mappingStatus: "mapped",
    assertion: "Existence",
    risk: "low",
  },
  {
    id: "tb22",
    accountNumber: "3100",
    accountName: "Additional Paid-In Capital",
    debit: 0,
    credit: 3400000,
    mapping: "Additional paid-in capital",
    mappingStatus: "mapped",
    assertion: "Existence",
    risk: "low",
  },
  {
    id: "tb23",
    accountNumber: "3200",
    accountName: "Retained Earnings",
    debit: 0,
    credit: 8920500,
    mapping: "Retained earnings",
    mappingStatus: "mapped",
    assertion: "Accuracy",
    risk: "low",
  },
  {
    id: "tb24",
    accountNumber: "4000",
    accountName: "Product Revenue",
    debit: 0,
    credit: 18420000,
    mapping: "Revenue",
    mappingStatus: "mapped",
    assertion: "Occurrence; Completeness; Cutoff",
    risk: "high",
  },
  {
    id: "tb25",
    accountNumber: "4100",
    accountName: "Service Revenue",
    debit: 0,
    credit: 4280000,
    mapping: "Revenue",
    mappingStatus: "mapped",
    assertion: "Occurrence; Completeness; Cutoff",
    risk: "high",
  },
  {
    id: "tb26",
    accountNumber: "5000",
    accountName: "COGS — Materials",
    debit: 7240000,
    credit: 0,
    mapping: "Cost of goods sold",
    mappingStatus: "mapped",
    assertion: "Occurrence; Accuracy",
    risk: "medium",
  },
  {
    id: "tb27",
    accountNumber: "5100",
    accountName: "COGS — Labor",
    debit: 4820000,
    credit: 0,
    mapping: "Cost of goods sold",
    mappingStatus: "mapped",
    assertion: "Occurrence; Accuracy",
    risk: "medium",
  },
  {
    id: "tb28",
    accountNumber: "5200",
    accountName: "COGS — Overhead",
    debit: 3210000,
    credit: 0,
    mapping: "Cost of goods sold",
    mappingStatus: "mapped",
    assertion: "Occurrence; Accuracy",
    risk: "medium",
  },
  {
    id: "tb29",
    accountNumber: "6000",
    accountName: "Salaries & Wages",
    debit: 2840000,
    credit: 0,
    mapping: "Operating expenses",
    mappingStatus: "mapped",
    assertion: "Occurrence; Accuracy",
    risk: "low",
  },
  {
    id: "tb30",
    accountNumber: "6100",
    accountName: "Rent Expense",
    debit: 640000,
    credit: 0,
    mapping: "Operating expenses",
    mappingStatus: "mapped",
    assertion: "Occurrence; Accuracy",
    risk: "low",
  },
  {
    id: "tb31",
    accountNumber: "6200",
    accountName: "Depreciation Expense",
    debit: 820000,
    credit: 0,
    mapping: "Operating expenses",
    mappingStatus: "mapped",
    assertion: "Accuracy",
    risk: "low",
  },
  {
    id: "tb32",
    accountNumber: "6300",
    accountName: "Professional Services",
    debit: 340000,
    credit: 0,
    mapping: null,
    mappingStatus: "unmapped",
    assertion: null,
    risk: "low",
  },
  {
    id: "tb33",
    accountNumber: "6400",
    accountName: "Marketing & Advertising",
    debit: 580000,
    credit: 0,
    mapping: "Operating expenses",
    mappingStatus: "mapped",
    assertion: "Occurrence",
    risk: "low",
  },
  {
    id: "tb34",
    accountNumber: "7000",
    accountName: "Interest Expense",
    debit: 142000,
    credit: 0,
    mapping: "Interest expense",
    mappingStatus: "mapped",
    assertion: "Accuracy",
    risk: "low",
  },
  {
    id: "tb35",
    accountNumber: "7100",
    accountName: "Foreign Exchange Gain/Loss",
    debit: 38000,
    credit: 0,
    mapping: null,
    mappingStatus: "unmapped",
    assertion: null,
    risk: "medium",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "a1",
    actor: "Jordan Avery",
    actorInitials: "JA",
    action: "approved working paper",
    target: "F-1 Fixed Assets Roll-Forward",
    timestamp: "2025-05-20T14:32:00",
    type: "sign-off",
  },
  {
    id: "a2",
    actor: "Kai Patel",
    actorInitials: "KP",
    action: "uploaded version 3 of",
    target: "Bank Confirmations — First National",
    timestamp: "2025-05-20T11:15:00",
    type: "document",
  },
  {
    id: "a3",
    actor: "Jordan Avery",
    actorInitials: "JA",
    action: "cleared review note on",
    target: "B-1 Accounts Receivable — Aging",
    timestamp: "2025-05-19T16:45:00",
    type: "note",
  },
  {
    id: "a4",
    actor: "Lina Ortiz",
    actorInitials: "LO",
    action: "prepared working paper",
    target: "A-2 Bank Confirmations Summary",
    timestamp: "2025-05-19T09:20:00",
    type: "sign-off",
  },
  {
    id: "a5",
    actor: "Jordan Avery",
    actorInitials: "JA",
    action: "mapped 32 trial balance accounts on",
    target: "FY2025 Statutory Audit",
    timestamp: "2025-05-18T15:10:00",
    type: "mapping",
  },
  {
    id: "a6",
    actor: "Kai Patel",
    actorInitials: "KP",
    action: "added review note to",
    target: "A-1 Cash & Cash Equivalents",
    timestamp: "2025-05-18T10:05:00",
    type: "note",
  },
  {
    id: "a7",
    actor: "Sarah Whitman",
    actorInitials: "SW",
    action: "updated engagement status for",
    target: "Q4 Internal Controls Review",
    timestamp: "2025-05-17T13:40:00",
    type: "engagement",
  },
  {
    id: "a8",
    actor: "Ben Foster",
    actorInitials: "BF",
    action: "uploaded version 2 of",
    target: "Fixed Asset Roll-Forward",
    timestamp: "2025-05-17T08:30:00",
    type: "document",
  },
];

export const statusConfig: Record<
  string,
  { label: string; color: string; dot: string }
> = {
  planning: {
    label: "Planning",
    color: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
    dot: "bg-blue-500",
  },
  fieldwork: {
    label: "Fieldwork",
    color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
    dot: "bg-amber-500",
  },
  review: {
    label: "In Review",
    color:
      "bg-purple-100 text-purple-700 dark:bg-purple-950 dark:text-purple-300",
    dot: "bg-purple-500",
  },
  "sign-off": {
    label: "Sign-off",
    color: "bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300",
    dot: "bg-cyan-500",
  },
  completed: {
    label: "Completed",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
    dot: "bg-emerald-500",
  },
};

export const signOffConfig: Record<string, { label: string; color: string }> = {
  pending: { label: "Pending", color: "bg-muted text-muted-foreground" },
  prepared: {
    label: "Prepared",
    color: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",
  },
  reviewed: {
    label: "Reviewed",
    color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
  },
  approved: {
    label: "Approved",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
  },
};

export const riskConfig: Record<string, { label: string; color: string }> = {
  low: {
    label: "Low",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
  },
  medium: {
    label: "Medium",
    color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
  },
  high: {
    label: "High",
    color: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300",
  },
};

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: "partner" | "manager" | "senior" | "staff";
  status: "active" | "invited" | "inactive";
  initials: string;
  color: string;
  engagements: number;
  hoursThisWeek: number;
  joinedAt: string;
  lastActive: string;
  specializations: string[];
}

export const teamMembers: TeamMember[] = [
  {
    id: "tm1",
    name: "Sarah Whitman",
    email: "sarah.whitman@northgate.io",
    role: "partner",
    status: "active",
    initials: "SW",
    color: "from-sky-400 to-blue-500",
    engagements: 3,
    hoursThisWeek: 38,
    joinedAt: "2023-01-15",
    lastActive: "2025-05-20T14:30:00",
    specializations: [
      "Financial Statement Audit",
      "Manufacturing",
      "SOX Compliance",
    ],
  },
  {
    id: "tm2",
    name: "Jordan Avery",
    email: "jordan.avery@northgate.io",
    role: "manager",
    status: "active",
    initials: "JA",
    color: "from-emerald-400 to-teal-500",
    engagements: 5,
    hoursThisWeek: 44,
    joinedAt: "2023-03-01",
    lastActive: "2025-05-20T16:45:00",
    specializations: ["Engagement Management", "Working Papers", "Review"],
  },
  {
    id: "tm3",
    name: "David Cho",
    email: "david.cho@northgate.io",
    role: "partner",
    status: "active",
    initials: "DC",
    color: "from-violet-400 to-purple-500",
    engagements: 3,
    hoursThisWeek: 36,
    joinedAt: "2023-02-10",
    lastActive: "2025-05-20T11:20:00",
    specializations: ["Logistics", "Compliance Audit", "SOC Reports"],
  },
  {
    id: "tm4",
    name: "Kai Patel",
    email: "kai.patel@northgate.io",
    role: "senior",
    status: "active",
    initials: "KP",
    color: "from-amber-400 to-orange-500",
    engagements: 2,
    hoursThisWeek: 41,
    joinedAt: "2023-06-15",
    lastActive: "2025-05-20T15:10:00",
    specializations: ["Cash & Banking", "Inventory", "Fieldwork"],
  },
  {
    id: "tm5",
    name: "Lina Ortiz",
    email: "lina.ortiz@northgate.io",
    role: "senior",
    status: "active",
    initials: "LO",
    color: "from-pink-400 to-rose-500",
    engagements: 2,
    hoursThisWeek: 39,
    joinedAt: "2023-08-20",
    lastActive: "2025-05-19T17:30:00",
    specializations: ["Receivables", "Revenue Recognition", "Healthcare"],
  },
  {
    id: "tm6",
    name: "Maya Singh",
    email: "maya.singh@northgate.io",
    role: "staff",
    status: "active",
    initials: "MS",
    color: "from-cyan-400 to-sky-500",
    engagements: 2,
    hoursThisWeek: 35,
    joinedAt: "2024-01-10",
    lastActive: "2025-05-20T09:15:00",
    specializations: ["Compliance", "Controls Testing"],
  },
  {
    id: "tm7",
    name: "Ben Foster",
    email: "ben.foster@northgate.io",
    role: "staff",
    status: "active",
    initials: "BF",
    color: "from-indigo-400 to-blue-500",
    engagements: 2,
    hoursThisWeek: 37,
    joinedAt: "2024-02-01",
    lastActive: "2025-05-20T13:00:00",
    specializations: ["Fixed Assets", "Depreciation", "Logistics"],
  },
  {
    id: "tm8",
    name: "Alex Romano",
    email: "alex.romano@northgate.io",
    role: "staff",
    status: "invited",
    initials: "AR",
    color: "from-slate-400 to-gray-500",
    engagements: 0,
    hoursThisWeek: 0,
    joinedAt: "2025-05-20",
    lastActive: "",
    specializations: [],
  },
];

export const roleConfig: Record<
  string,
  { label: string; color: string; description: string }
> = {
  partner: {
    label: "Partner",
    color:
      "bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300",
    description:
      "Full access — owns engagements, approves sign-offs, manages the firm",
  },
  manager: {
    label: "Manager",
    color: "bg-sky-100 text-sky-700 dark:bg-sky-950 dark:text-sky-300",
    description:
      "Manages engagements, reviews working papers, oversees fieldwork",
  },
  senior: {
    label: "Senior",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
    description: "Prepares working papers, leads fieldwork, supervises staff",
  },
  staff: {
    label: "Staff",
    color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
    description: "Supports fieldwork, gathers evidence, performs testing",
  },
};

export const memberStatusConfig: Record<
  string,
  { label: string; color: string; dot: string }
> = {
  active: {
    label: "Active",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",
    dot: "bg-emerald-500",
  },
  invited: {
    label: "Invited",
    color: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",
    dot: "bg-amber-500",
  },
  inactive: {
    label: "Inactive",
    color: "bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400",
    dot: "bg-gray-400",
  },
};

export function getClient(id: string): Client | undefined {
  return clients.find((c) => c.id === id);
}

export function getEngagementsByClient(clientId: string): Engagement[] {
  return engagements.filter((e) => e.clientId === clientId);
}

export function getDocumentsByEngagement(engagementId: string): Document[] {
  return documents.filter((d) => d.engagementId === engagementId);
}

export function getWorkingPapersByEngagement(
  engagementId: string,
): WorkingPaper[] {
  return workingPapers.filter((wp) => wp.engagementId === engagementId);
}

export function getEngagement(id: string): Engagement | undefined {
  return engagements.find((e) => e.id === id);
}
