<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledgance.TestInfrastructure\Ledgance.TestInfrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Accounting\AI\Ledgance.Accounting.AI.Application\Ledgance.Accounting.AI.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Accounting\Client\Ledgance.Accounting.Client.Application\Ledgance.Accounting.Client.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Accounting\Organization\Ledgance.Accounting.Organization.Application\Ledgance.Accounting.Organization.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Accounting\User\Ledgance.Accounting.User.Application\Ledgance.Accounting.User.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
